// Hermes mod strings — русская локализация мода.
// Английский живёт в fallback.strings.

const RU: Record<string, string> = {
  EthernetModSettings: 'Настройки мода',
  EthernetThemes: 'Темы',
  EthernetThemesDesc: 'Свои стили, CSS-редактор',
  EthernetThemesHint: 'Нажмите на тему, чтобы применить. Темы переопределяют CSS-переменные клиента.',
  EthernetThemeActive: 'Активна',
  EthernetThemeDefault: 'Обычная',
  EthernetThemeSelection: 'Выбор темы',
  EthernetImportCssFile: 'Импортировать CSS-файл...',
  EthernetNewTheme: 'Новая тема (CSS-редактор)',
  EthernetEditTheme: 'Изменить тему',
  EthernetThemeName: 'Название темы',
  EthernetDeleteThemeConfirm: 'Удалить эту тему?',
  EthernetPlugins: 'Плагины',
  EthernetPluginsDesc: 'Расширяйте клиент JS-кодом',
  EthernetPluginsHint: 'Плагины исполняются в контексте страницы. Устанавливайте только код, которому доверяете.',
  EthernetImportJsFile: 'Импортировать JS-файл...',
  EthernetNewPlugin: 'Новый плагин',
  EthernetEditPlugin: 'Изменить плагин',
  EthernetPluginName: 'Название плагина',
  EthernetPluginDescription: 'Описание',
  EthernetDeletePluginConfirm: 'Удалить этот плагин?',
  EthernetThemeEditor: 'Редактор темы',
  EthernetThemeEditorDesc: 'Цвета, блюр, анимации, обои',
  EthernetImportTheme: 'Импортировать тему...',
  EthernetExportTheme: 'Экспортировать тему',
  EthernetSectionMain: 'Основные настройки',
  EthernetSectionColors: 'Цвета',
  EthernetSectionRounding: 'Скругления',
  EthernetSectionBlur: 'Блюр',
  EthernetSectionWallpaper: 'Обои',
  EthernetSectionAnimations: 'Анимации',
  EthernetBorderRadius: 'Радиус скруглений',
  EthernetRadiusUi: 'Интерфейс и панели',
  EthernetRadiusMessages: 'Пузыри сообщений',
  EthernetRadiusButtons: 'Кнопки и поля ввода',
  EthernetRadiusAvatars: 'Аватары (%)',
  EthernetColorBackground: 'Фон',
  EthernetColorBackgroundSecondary: 'Вторичный фон',
  EthernetColorBackgroundSidebar: 'Боковая панель',
  EthernetColorText: 'Текст',
  EthernetColorPrimary: 'Акцентный цвет',
  EthernetColorBackgroundOwn: 'Свои сообщения',
  EthernetColorChatActive: 'Активный чат',
  EthernetEyedropper: 'Пипетка',
  EthernetResetColor: 'Сбросить цвет',
  EthernetBlurStrength: 'Сила блюра',
  EthernetWallpaperPick: 'Выбрать файл...',
  EthernetWallpaperClear: 'Убрать',
  EthernetWallpaperHint: 'Поддерживаются PNG, JPEG, WebP, GIF и видео MP4/WebM. Видео-обои проигрываются зацикленно без звука.',
  EthernetColorLinks: 'Цветной текст (ссылки, теги)',
  EthernetBlurSidebar: 'Боковая панель',
  EthernetBlurHeader: 'Шапка чата',
  EthernetBlurBubbles: 'Пузыри сообщений',
  EthernetBlurMenus: 'Меню и диалоги',
  EthernetAlignOwn: 'Свои сообщения',
  EthernetAlignOther: 'Сообщения собеседника',
  EthernetAlignLeft: 'Слева',
  EthernetAlignRight: 'Справа',
  EthernetAlignCenter: 'По центру',
  EthernetActionSave: 'Сохранить',
  EthernetActionImport: 'Импорт',
  EthernetActionExport: 'Экспорт',
  EthernetActionCreate: 'Создать',
  EthernetSaveCurrentTheme: 'Сохранить текущую тему',
  EthernetSaveThemePlaceholder: 'Название темы (например: Неон, Аметист...)',
  EthernetCustomTheme: 'Кастомная тема',
  EthernetEditInEditor: 'Редактировать в редакторе',
  EthernetExportCss: 'Экспортировать (.css)',
  EthernetCodeCss: 'Код (CSS)',
  EthernetAnimationsOff: 'Отключить анимации',
  EthernetAnimationSpeed: 'Длительность анимаций (мс)',
  EthernetAnimationCurve: 'Кривая анимации',
  EthernetSectionLayout: 'Ширина чата',
  EthernetWidthDefault: 'Обычная',
  EthernetWidthWide: 'Широкая',
  EthernetWidthFull: 'На всю ширину',
};

export default RU;
