import type { LangFn } from './localization';

const DICTIONARY: Record<string, { ru: string; en: string }> = {
  EthernetModSettings: { ru: 'Настройки Ethernet', en: 'Mod settings' },
  EthernetFunctions: { ru: 'Функции', en: 'Functions' },
  EthernetFunctionsDesc: { ru: 'Режим призрака, твики и скрытность', en: 'Ghost mode, tweaks and privacy' },
  EthernetNetwork: { ru: 'Сеть', en: 'Network' },
  EthernetNetworkDesc: { ru: 'Прокси, соединение и ускорение', en: 'Proxy, connection and acceleration' },
  EthernetThemes: { ru: 'Темы', en: 'Themes' },
  EthernetThemesDesc: { ru: 'Пользовательские стили, редактор CSS', en: 'Custom styles, CSS editor' },
  EthernetThemesHint: { ru: 'Нажмите на тему, чтобы применить её. Темы переопределяют CSS-переменные клиента.', en: 'Click a theme to apply it. Themes override CSS variables of the client.' },
  EthernetThemeActive: { ru: 'Активная', en: 'Active' },
  EthernetImportCssFile: { ru: 'Импортировать файл CSS...', en: 'Import CSS file...' },
  EthernetNewTheme: { ru: 'Новая тема (редактор CSS)', en: 'New theme (CSS editor)' },
  EthernetEditTheme: { ru: 'Редактировать тему', en: 'Edit theme' },
  EthernetThemeName: { ru: 'Название темы', en: 'Theme name' },
  EthernetDeleteThemeConfirm: { ru: 'Вы уверены, что хотите удалить эту тему?', en: 'Are you sure you want to delete this theme?' },
  EthernetPlugins: { ru: 'Плагины', en: 'Plugins' },
  EthernetPluginsDesc: { ru: 'Расширение клиента на JS', en: 'Extend the client with JS' },
  EthernetPluginsHint: { ru: 'Плагины выполняются в контексте страницы. Устанавливайте только проверенный код.', en: 'Plugins run in the page context. Only install code you trust.' },
  EthernetThemeChannel: { ru: '@ethTheme', en: '@ethTheme' },
  EthernetThemeChannelDesc: { ru: 'Канал с темами для Ethernet', en: 'Themes channel for Ethernet' },
  EthernetPluginChannel: { ru: '@ethPlugin', en: '@ethPlugin' },
  EthernetPluginChannelDesc: { ru: 'Канал с плагинами для Ethernet', en: 'Plugins channel for Ethernet' },
  EthernetSafeMode: { ru: 'Безопасный режим', en: 'Safe Mode' },
  EthernetSafeModeDesc: { ru: 'Отключает все плагины. Включается автоматически при ошибках и сбоях в коде плагинов.', en: 'Disables all plugins. Automatically enabled on plugin errors/crashes.' },
  EthernetSafeModeActive: { ru: 'Безопасный режим активен — все плагины временно отключены', en: 'Safe Mode active — all plugins are disabled' },
  EthernetImportJsFile: { ru: 'Импортировать файл JS...', en: 'Import JS file...' },
  EthernetNewPlugin: { ru: 'Новый плагин', en: 'New plugin' },
  EthernetEditPlugin: { ru: 'Редактировать плагин', en: 'Edit plugin' },
  EthernetPluginName: { ru: 'Название плагина', en: 'Plugin name' },
  EthernetPluginDescription: { ru: 'Описание', en: 'Description' },
  EthernetDeletePluginConfirm: { ru: 'Вы уверены, что хотите удалить этот плагин?', en: 'Are you sure you want to delete this plugin?' },
  EthernetExperimental: { ru: 'Экспериментальные', en: 'Experimental' },
  EthernetExperimentalDesc: { ru: 'Экспериментальные возможности Telegram', en: 'Telegram experimental features' },
  EthernetAuthorChannel: { ru: '@ethernetgram', en: '@ethernetgram' },
  EthernetAuthorChannelDesc: { ru: 'Официальный канал', en: 'Official channel and updates' },
  EthernetThemeEditor: { ru: 'Редактор тем', en: 'Theme Editor' },
  EthernetThemeEditorDesc: { ru: 'Цвета, скругления, блюр, обои', en: 'Colors, blur, animations, wallpaper' },
  EthernetImportTheme: { ru: 'Импортировать тему...', en: 'Import theme...' },
  EthernetExportTheme: { ru: 'Экспортировать тему', en: 'Export theme' },
  EthernetSaveCurrentTheme: { ru: 'Сохранить текущую тему', en: 'Save current theme' },
  EthernetActionSave: { ru: 'Сохранить', en: 'Save' },
  EthernetActionImport: { ru: 'Импорт', en: 'Import' },
  EthernetActionExport: { ru: 'Экспорт', en: 'Export' },
  EthernetActionCreate: { ru: 'Создать', en: 'Create' },
  EthernetEditInEditor: { ru: 'Редактировать в Theme Editor', en: 'Edit in Theme Editor' },
  EthernetExportCss: { ru: 'Экспорт в файл .css', en: 'Export to .css file' },
  EthernetEditCssCode: { ru: 'Редактировать CSS-код', en: 'Edit CSS code' },
  EthernetDeleteTheme: { ru: 'Удалить тему', en: 'Delete theme' },
  EthernetThemeCode: { ru: 'CSS-код темы', en: 'Theme CSS code' },
  EthernetSectionMain: { ru: 'Основные настройки', en: 'Main settings' },
  EthernetSectionColors: { ru: 'Цвета', en: 'Colors' },
  EthernetSectionRounding: { ru: 'Скругления', en: 'Rounding' },
  EthernetSectionBlur: { ru: 'Блюр', en: 'Blur' },
  EthernetSectionWallpaper: { ru: 'Обои', en: 'Wallpaper' },
  EthernetSectionAnimations: { ru: 'Анимации', en: 'Animations' },
  EthernetBorderRadius: { ru: 'Радиус скругления', en: 'Corner radius' },
  EthernetRadiusUi: { ru: 'Интерфейс и панели', en: 'Interface & Panels' },
  EthernetRadiusMessages: { ru: 'Сообщения', en: 'Message bubbles' },
  EthernetRadiusButtons: { ru: 'Кнопки и поля ввода', en: 'Buttons & inputs' },
  EthernetRadiusAvatars: { ru: 'Аватарки (%)', en: 'Avatars (%)' },
  EthernetColorBackground: { ru: 'Фон', en: 'Background' },
  EthernetColorBackgroundSecondary: { ru: 'Вторичный фон', en: 'Secondary background' },
  EthernetColorBackgroundSidebar: { ru: 'Фон сайдбара', en: 'Sidebar background' },
  EthernetColorText: { ru: 'Текст', en: 'Text' },
  EthernetColorLinks: { ru: 'Цветной текст и гиперссылки', en: 'Colored text & links' },
  EthernetColorTextSecondary: { ru: 'Вторичный текст (время, статус)', en: 'Secondary text (time, status)' },
  EthernetColorPrimary: { ru: 'Акцентный цвет', en: 'Accent' },
  EthernetColorTextMetaColored: { ru: 'Галочки прочтения сообщений', en: 'Read checkmarks' },
  EthernetColorBackgroundOwn: { ru: 'Свои сообщения', en: 'Own message bubble' },
  EthernetColorChatActive: { ru: 'Активный чат', en: 'Active chat' },
  EthernetThemeDefault: { ru: 'По умолчанию', en: 'Default' },
  EthernetThemeSelection: { ru: 'Выбор темы', en: 'Theme selection' },
  EthernetEyedropper: { ru: 'Пипетка', en: 'Eyedropper' },
  EthernetResetColor: { ru: 'Сбросить цвет', en: 'Reset color' },
  EthernetBlurStrength: { ru: 'Сила размытия', en: 'Blur strength' },
  EthernetBlurGlare: { ru: 'Сила блика', en: 'Glare strength' },
  EthernetBlurRefraction: { ru: 'Глубокое преломление', en: 'Deep refraction' },
  EthernetWallpaperPick: { ru: 'Выбрать файл...', en: 'Choose file...' },
  EthernetWallpaperClear: { ru: 'Удалить', en: 'Remove' },
  EthernetWallpaperHint: { ru: 'Поддерживаются PNG, JPEG, WebP, GIF и видео MP4/WebM. Видео воспроизводится зацикленно без звука.', en: 'Supports PNG, JPEG, WebP, GIF and video MP4/WebM. Video wallpapers play muted in a loop.' },
  EthernetAnimationsOff: { ru: 'Отключить анимации', en: 'Disable animations' },
  EthernetDisableSnapEffect: { ru: 'Отключить эффект рассеивания сообщений', en: 'Disable message disintegration (snap effect)' },
  EthernetAnimationSpeed: { ru: 'Длительность анимаций (мс)', en: 'Animation duration (ms)' },
  EthernetAnimationCurve: { ru: 'Кривая скорости', en: 'Easing curve' },
  EthernetWidthDefault: { ru: 'По умолчанию', en: 'Default' },
  EthernetWidthWide: { ru: 'Широкий', en: 'Wide' },
  EthernetWidthFull: { ru: 'На всю ширину', en: 'Full width' },
  EthernetBlurSidebar: { ru: 'Сайдбар', en: 'Sidebar' },
  EthernetBlurHeader: { ru: 'Шапка', en: 'Header' },
  EthernetBlurBubbles: { ru: 'Сообщения', en: 'Bubbles' },
  EthernetBlurMenus: { ru: 'Меню', en: 'Menus' },
  EthernetChatWidth: { ru: 'Ширина чата', en: 'Chat width' },
  EthernetMessageAlignOwn: { ru: 'Выравнивание своих сообщений', en: 'Own messages alignment' },
  EthernetMessageAlignOther: { ru: 'Выравнивание чужих сообщений', en: 'Other messages alignment' },
  EthernetAlignLeft: { ru: 'Слева', en: 'Left' },
  EthernetAlignCenter: { ru: 'По центру', en: 'Center' },
  EthernetAlignRight: { ru: 'Справа', en: 'Right' },
  EthernetInDevelopment: { ru: 'Раздел находится в разработке', en: 'Section is under development' },

  EthernetDisableAllNotifications: { ru: 'Выключить уведомления', en: 'Disable notifications' },
  EthernetDisableAllNotificationsDesc: { ru: 'Полностью отключает все всплывающие окна, звуки и уведомления о сообщениях и звонках', en: 'Completely disables all popups, sounds and notifications for messages and calls' },
  EthernetDisableCloseToTray: { ru: 'Не сворачивать в трей', en: 'Do not minimize to tray' },
  EthernetDisableCloseToTrayDesc: { ru: 'При нажатии на крестик окно приложения будет полностью закрываться, а не сворачиваться в системный трей', en: 'Clicking the close button (X) will completely quit the application instead of minimizing to tray' },

  EthernetOptimization: { ru: 'Оптимизация и производительность', en: 'Optimization & Performance' },
  EthernetDisableNftGifts: { ru: 'Отключить рендеринг NFT-подарков', en: 'Disable NFT gifts rendering' },
  EthernetDisableNftGiftsDesc: { ru: 'Снижает нагрузку на процессор и видеокарту на слабых ПК, отключая отрисовку и анимацию NFT-подарков', en: 'Reduces CPU and GPU usage on low-end systems by skipping NFT gift rendering and animations' },

  // Ghost Mode
  GhostEssentials: { ru: 'Основные функции призрака', en: 'Ghost essentials' },
  GhostMode: { ru: 'Режим невидимки', en: 'Ghost Mode' },
  GhostGlobalSettings: { ru: 'Глобальные настройки', en: 'Global Settings' },
  GhostDontReadMessages: { ru: 'Не читать сообщения', en: "Don't Read Messages" },
  GhostDontReadStories: { ru: 'Не смотреть истории', en: "Don't Read Stories" },
  GhostDontSendOnline: { ru: 'Не отправлять "В сети"', en: "Don't Send Online" },
  GhostDontSendTyping: { ru: 'Скрывать "Печатает..."', en: "Don't Send Typing" },
  GhostGoOfflineAuto: { ru: 'Автоматический офлайн', en: 'Go Offline Automatically' },
  GhostReadOnInteract: { ru: 'Читать при взаимодействии', en: 'Read on Interact' },
  GhostScheduleMessages: { ru: 'Отложенная отправка', en: 'Schedule Messages' },
  GhostScheduleMessagesDesc: {
    ru: 'Автоматически отправляет исходящие сообщения через ~12 секунд (дольше для медиа). При использовании этой функции вы не появитесь "В сети".',
    en: 'Automatically schedules outgoing messages to send after ~12 seconds (longer for media). Using this feature, you won\'t appear online. Avoid using on unreliable networks.',
  },
  GhostSendWithoutSound: { ru: 'Отправка без звука', en: 'Send without Sound' },
  SoundNever: { ru: 'Никогда', en: 'Never' },
  SoundAlways: { ru: 'Всегда', en: 'Always' },
  SoundGroupsOnly: { ru: 'Только в группах', en: 'Only in groups' },

  // Spy Essentials
  SpyEssentials: { ru: 'Шпионские функции', en: 'Spy essentials' },
  SpySaveDeletedMessages: { ru: 'Сохранять удаленные сообщения', en: 'Save Deleted Messages' },
  SpySaveEditsHistory: { ru: 'Сохранять историю изменений', en: 'Save Edits History' },
  SpySaveInBotDialogs: { ru: 'Сохранять в диалогах с ботами', en: 'Save in Bot Dialogs' },

  // Ads
  EthernetDisableAds: { ru: 'Отключить рекламу', en: 'Disable Ads' },

  // Edit History
  EthernetEditHistory: { ru: 'История изменений', en: 'History' },
  EthernetOriginalMessage: { ru: 'Оригинал', en: 'Original' },
  EthernetRevision: { ru: 'Редакция', en: 'Revision' },
  EthernetCurrentVersion: { ru: 'Текущая версия', en: 'Current version' },

  // Experimental
  ExperimentalLoginTestServer: { ru: 'Войти на тестовый сервер', en: 'Login on Test Server' },
  ExperimentalLaunchConfetti: { ru: 'Запустить конфетти!', en: 'Launch some confetti!' },
  ExperimentalStartWave: { ru: 'Запустить волну', en: 'Start wave' },
  ExperimentalVaporizeButton: { ru: 'Распылить эту кнопку', en: 'Vaporize this button' },
  ExperimentalAllowHttpTransport: { ru: 'Разрешить HTTP-транспорт', en: 'Allow HTTP Transport' },
  ExperimentalForceHttpTransport: { ru: 'Принудительный HTTP-транспорт', en: 'Force HTTP Transport' },
  ExperimentalEnableSendersDebug: { ru: 'Включить отладку экспортированных отправителей', en: 'Enable exported senders debug' },
  ExperimentalDownloadLog: { ru: 'Скачать лог', en: 'Download log' },

  // Proxy / Network
  ProxySettings: { ru: 'Настройки прокси', en: 'Proxy Settings' },
  ProxyUseInApp: { ru: 'Использовать прокси в приложении', en: 'Use in-app proxy' },
  ProxyUseInAppDesc: {
    ru: 'Маршрутизирует только трафик клиента Telegram, не затрагивая другие приложения в системе.',
    en: 'Routes only Telegram client traffic without affecting other apps in the system.',
  },
  ProxyActive: { ru: 'Активно', en: 'Active' },
  ProxyDirect: { ru: 'Прямое подключение', en: 'Direct connection' },
  ProxyConnected: { ru: 'Подключено', en: 'Connected' },
  ProxyConnecting: { ru: 'Подключение...', en: 'Connecting...' },
  ProxyDisconnected: { ru: 'Отключено', en: 'Disconnected' },
  ProxyAdd: { ru: 'Добавить прокси', en: 'Add proxy' },
  ProxyEdit: { ru: 'Редактировать прокси', en: 'Edit proxy' },
  ProxyImportLink: { ru: 'Импорт по ссылке', en: 'Import from link' },
  ProxyManual: { ru: 'Вручную', en: 'Manual' },
  ProxyLinkPlaceholder: {
    ru: 'Вставьте ссылку (socks5://..., http://..., tg://socks?...)...',
    en: 'Paste proxy link (socks5://..., http://..., tg://socks?...)...',
  },
  ProxyName: { ru: 'Название', en: 'Name' },
  ProxyProtocol: { ru: 'Протокол', en: 'Protocol' },
  ProxyServer: { ru: 'Сервер (IP или домен)', en: 'Server (IP or domain)' },
  ProxyPort: { ru: 'Порт', en: 'Port' },
  ProxyUsername: { ru: 'Имя пользователя', en: 'Username' },
  ProxyPassword: { ru: 'Пароль', en: 'Password' },
  ProxyOptional: { ru: 'Необязательно', en: 'Optional' },
  ProxyTestPing: { ru: 'Проверить пинг', en: 'Test ping' },
  ProxyDelete: { ru: 'Удалить', en: 'Delete' },
  ProxyDeleteConfirm: { ru: 'Вы уверены, что хотите удалить этот прокси?', en: 'Are you sure you want to delete this proxy?' },
  ProxyListEmpty: {
    ru: 'Список прокси пуст. Нажмите «Добавить прокси», чтобы добавить сервер.',
    en: 'No proxies added. Click "Add proxy" to add a server.',
  },

  // Bypass / Обход (TG WS Proxy)
  BypassTitle: { ru: 'Обход', en: 'Bypass' },
  BypassSectionTitle: { ru: 'Встроенный TG WS Proxy', en: 'Built-in TG WS Proxy' },
  BypassSectionDesc: {
    ru: 'Автономный WSS-мост для прямого подключения к серверам Telegram без использования сторонних VPN.',
    en: 'Standalone WSS bridge for direct Telegram connection without external VPNs.',
  },
  BypassToggle: { ru: 'Использовать встроенный Обход', en: 'Use built-in Bypass' },
  BypassToggleDesc: {
    ru: 'Туннелирует трафик дата-центров Telegram через защищенные WebSocket-узлы.',
    en: 'Tunnels Telegram DC traffic through secure WebSocket nodes.',
  },
  BypassPort: { ru: 'Локальный порт', en: 'Local port' },
  BypassPortDesc: { ru: 'Порт внутреннего SOCKS5-сервера', en: 'Internal SOCKS5 server port' },
  BypassRestart: { ru: 'Перезапустить службу', en: 'Restart service' },
  BypassRunning: { ru: 'Служба работает', en: 'Service is running' },
  BypassStopped: { ru: 'Служба остановлена', en: 'Service stopped' },

  // Geo IP Card
  GeoNetworkTitle: { ru: 'Текущее сетевое подключение', en: 'Current Network Connection' },
  GeoNetworkProtected: { ru: 'Трафик защищён (Обход)', en: 'Traffic Protected (Bypass)' },
  GeoNetworkCustomProxy: { ru: 'Через прокси', en: 'Via Proxy' },
  GeoNetworkDirect: { ru: 'Прямое подключение', en: 'Direct Connection' },
  GeoSpoilerClickToShow: { ru: 'Нажмите, чтобы показать IP', en: 'Click to show IP' },
  GeoSpoilerClickToHide: { ru: 'Нажмите, чтобы скрыть IP', en: 'Click to hide IP' },
  GeoRefresh: { ru: 'Проверить соединение', en: 'Check connection' },
  GeoCopied: { ru: 'IP-адрес скопирован', en: 'IP copied to clipboard' },
  CustomProxiesTitle: { ru: 'Пользовательские прокси (SOCKS5 / HTTP)', en: 'Custom Proxies (SOCKS5 / HTTP)' },

  // Documentation
  EthernetActionDocs: { ru: 'Справка', en: 'Docs' },
  EthernetDocsTitle: { ru: 'Документация: Темы и Плагины', en: 'Documentation: Themes & Plugins' },
  EthernetTabThemes: { ru: 'Темы (CSS)', en: 'Themes (CSS)' },
  EthernetTabPlugins: { ru: 'Плагины (JS)', en: 'Plugins (JS)' },
  EthernetTabAi: { ru: 'API для ИИ / LLM', en: 'AI / LLM API' },
  EthernetTabExamples: { ru: 'Готовые примеры', en: 'Examples' },
  EthernetCopyMd: { ru: 'Скопировать .MD', en: 'Copy .MD' },
  EthernetCopied: { ru: 'Скопировано в буфер обмена!', en: 'Copied to clipboard!' },
  EthernetMarkAsRead: { ru: 'Прочитать', en: 'Mark as read' },
};

export function getEthernetString(lang: LangFn | undefined, key: string): string {
  const rawCode = (lang as any)?.code || (lang as any)?.rawCode || document.documentElement.lang || 'ru';
  const isRu = typeof rawCode === 'string' ? rawCode.toLowerCase().startsWith('ru') : true;
  const entry = DICTIONARY[key];
  if (entry) {
    return isRu ? entry.ru : entry.en;
  }
  return lang ? lang(key) : key;
}
